### PR TITLE
allow customize numbering and supplement for mitex/mi

### PR DESCRIPTION
**Pull request by Enter-tainer**

### CODE REVIEW

**Comment by OrangeX4** [comment]
We can now do this by

```typst
#set math.equation(numbering: "(1)")

#mitex(`
  f(x) = \int_{-\infty}^\infty
    \hat f(\xi)\,e^{2 \pi i \xi x}
    \,d\xi
`) <eqt>
```

Just like the normal way of using typst.

But if we set the default values for numbering and supplement, this normal way will not work.

Is there a way to do both: using a normal set rule and also having the ability of passing arguments?

**Comment by Enter-tainer** [comment]
We can assume that `#mitex` is not `math.equation` so one should use `#set mitex(numbering: (1))` if they want to have numbers by default.

**Comment by Enter-tainer** [comment]
passing arguments explicitly is useful when you want to number equations by hand. For example you only want to number some of your equations

**Comment by OrangeX4** [comment]
Maybe we can add condition control? For example, the default parameter is auto, and if it detects that it is auto, arguments will not be passed to `math.equation`.

**Comment by Enter-tainer** [comment]
that make sense, I will fix that

**Comment by Enter-tainer** [comment]
BTW the default value for `numbering` in `math.equation` is `none` https://typst.app/docs/reference/math/equation/#parameters-numbering.

I guess the auto might make sense in some case but i didn't think too much. Just let you know about this.

**Pull request merged**
